WITH no_rest_countries AS (
  SELECT
    cwms.id,
    cwms.left_country_table,
    cwms.left_country_table_field_name,
    cwms.left_country_id,
    cwms.left_country_name,
    cwms.right_country_table,
    cwms.right_country_table_field_name,
    cwms.right_country_id,
    cwms.right_country_name,
    cwms.ratio,
    cwms.token_set_ratio,
    cwms.maximum_score
  FROM
    calculations_with_max_scores cwms
  WHERE
    (
      cwms.left_country_table <> 'rest_countries_api_data_names' :: text
    )
),
with_new_data AS (
  SELECT
    no_rest_countries.id,
    no_rest_countries.left_country_table,
    no_rest_countries.left_country_table_field_name,
    no_rest_countries.left_country_id,
    no_rest_countries.left_country_name,
    no_rest_countries.right_country_table,
    no_rest_countries.right_country_table_field_name,
    no_rest_countries.right_country_id,
    no_rest_countries.right_country_name,
    no_rest_countries.ratio,
    no_rest_countries.token_set_ratio,
    no_rest_countries.maximum_score
  FROM
    no_rest_countries
  UNION
  ALL
  SELECT
    rest_countries_calculations_aggregated.id,
    rest_countries_calculations_aggregated.left_country_table,
    rest_countries_calculations_aggregated.left_country_table_field_name,
    rest_countries_calculations_aggregated.left_country_id,
    rest_countries_calculations_aggregated.left_country_name,
    rest_countries_calculations_aggregated.right_country_table,
    rest_countries_calculations_aggregated.right_country_table_field_name,
    rest_countries_calculations_aggregated.right_country_id,
    rest_countries_calculations_aggregated.right_country_name,
    rest_countries_calculations_aggregated.ratio,
    rest_countries_calculations_aggregated.token_set_ratio,
    rest_countries_calculations_aggregated.maximum_score
  FROM
    rest_countries_calculations_aggregated
)
SELECT
  with_new_data.id,
  with_new_data.left_country_table,
  with_new_data.left_country_table_field_name,
  with_new_data.left_country_id,
  with_new_data.left_country_name,
  with_new_data.right_country_table,
  with_new_data.right_country_table_field_name,
  with_new_data.right_country_id,
  with_new_data.right_country_name,
  with_new_data.ratio,
  with_new_data.token_set_ratio,
  with_new_data.maximum_score
FROM
  with_new_data;