# fly.toml app configuration file generated for 5-star-tasker on 2024-01-27T20:54:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '5-star-tasker'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
