# fly.toml app configuration file generated for 5-star-backend on 2023-09-03T18:49:36-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "5-star-backend"
primary_region = "lax"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
