export const emojiMap:Record<string,string> = {
    "🇨🇱":"ES",
    "🇨🇼":"NL",
    "🇳🇱":"NL",
    "🇨🇻":"PT",
    "🇦🇷":"ES",
    "🇫🇰":"EN",
    "🇱🇻":"LV",
    "🇷🇺":"RU",
    "🇻🇬":"EN",
    "🇧🇶":"NL",
    "🇨🇮":"FR",
    "🇰🇷":"KO",
    "🇱🇹":"LT",
    "🇮🇩":"ID",
    "🇷🇴":"RO",
    "🇨🇺":"ES",
    "🇧🇫":"FR",
    "🇮🇨":"ES",
    "🇨🇦":"EN",
    "🇦🇺":"EN",
    "🇩🇴":"ES",
    "🇬🇷":"EL",
    "🇧🇬":"BG",
    "🇬🇧":"EN",
    "🇿🇦":"EN",
    "🇸🇪":"SV",
    "🇰🇾":"EN",
    "🇪🇪":"ET",
    "🇩🇪":"DE",
    "🇫🇷":"FR",
    "🇧🇯":"FR",
    "🇦🇽":"DA",
    "🇨🇩":"FR",
    "🇵🇱":"PL",
    "🇩🇲":"EN",
    "🇧🇷":"PT",
    "🇦🇼":"NL",
    "🇧🇴":"ES",
    "🇯🇵":"JA",
    "🇦🇨":"EN",
    "🇩🇯":"FR",
    "🇮🇪":"EN",
    "🇨🇰":"EN",
    "🇧🇲":"EN",
    "🇮🇹":"IT",
    "🇦🇹":"DE",
    "🇧🇧":"EN",
    "🇳🇿":"EN",
    "🇧🇱":"EN",
    "🇦🇴":"PT",
    "🇸🇰":"SK",
    "🇧🇪":"NL",
    "🇭🇺":"HU",
    "🇫🇮":"FI",
    "🇵🇷":"ES",
    "🇲🇽":"ES",
    "🇪🇸":"ES",
    "🇨🇾":"EL",
    "🇨🇭":"DE",
    "🇧🇿":"EN",
    "🇧🇼":"EN",
    "🇹🇩":"FR",
    "🇦🇬":"EN",
    "🇨🇳":"ZH",
    "🇺🇸":"EN",
    "🇩🇰":"DA",
    "🇨🇫":"FR",
    "🇵🇹":"PT",
    "🇨🇷":"ES",
    "🇧🇸":"EN",
    "🇸🇮":"SL",
    "🇨🇬":"FR",
    "🇱🇺":"FR",
    "🇨🇨":"FR",
    "🇹🇼":"ZH",
    "🇭🇰":"ZH",
    "🇸🇬":"ZH",
    "🇲🇴":"ZH",
    "🇨🇴":"ES",
    "🇨🇲":"FR",
    "🇨🇿":"CS",
    "🇮🇴":"EN",
    "🇦🇶":"RU",
    "🇦🇮":"EN",
    "🇨🇽":"EN",
    "🇪🇺":"EN",
    "🇬🇶":"ES",
    "🇪🇨":"ES",
    "🇫🇴":"DA",
    "🇫🇯":"EN",
    "🇬🇫":"FR",
    "🇵🇫":"FR",
    "🇹🇫":"FR",
    "🇬🇦":"FR",
    "🇬🇲":"EN",
    "🇬🇺":"EN",
    "🇬🇵":"FR",
    "🇬🇩":"EN",
    "🇬🇱":"DA",
    "🇬🇮":"EN",
    "🇬🇭":"EN",
    "🇬🇹":"ES",
    "🇬🇬":"EN",
    "🇬🇳":"FR",
    "🇬🇼":"PT",
    "🇬🇾":"EN",
    "🇭🇹":"FR",
    "🇭🇳":"ES",
    "🇮🇲":"EN",
    "🇯🇲":"EN",
    "🇯🇪":"EN",
    "🇰🇮":"EN",
    "🇱🇮":"DE",
    "🇱🇷":"EN",
    "🇲🇻":"EN",
    "🇲🇱":"FR",
    "🇲🇩":"RO",
    "🇫🇲":"EN",
    "🇾🇹":"FR",
    "🇲🇺":"EN",
    "🇲🇶":"FR",
    "🇲🇭":"EN",
    "🇲🇨":"FR",
    "🇲🇪":"EN",
    "🇲🇿":"PT",
    "🇳🇦":"EN",
    "🇳🇷":"EN",
    "🇳🇨":"FR",
    "🇳🇮":"ES",
    "🇳🇬":"EN",
    "🇳🇺":"EN",
    "🇳🇫":"EN",
    "🇵🇬":"EN",
    "🇵🇦":"ES",
    "🇵🇼":"EN",
    "🇲🇵":"EN",
    "🇰🇵":"KO",
    "🇵🇾":"ES",
    "🇵🇪":"ES",
    "🇵🇳":"EN",
    "🇷🇪":"FR",
    "🇸🇳":"FR",
    "🇸🇹":"PT",
    "🇷🇼":"FR",
    "🇸🇨":"FR",
    "🇸🇽":"NL",
    "🇬🇸":"EN",
    "🇸🇧":"EN",
    "🇱🇨":"EN",
    "🇰🇳":"EN",
    "🇸🇭":"EN",
    "🇸🇸":"EN",
    "🇵🇲":"FR",
    "🇻🇨":"EN",
    "🇸🇿":"EN",
    "🇹🇹":"EN",
    "🇹🇴":"EN",
    "🇹🇰":"EN",
    "🇹🇬":"FR",
    "🇹🇱":"PT",
    "🇹🇷":"TR",
    "🇹🇲":"RU",
    "🇹🇨":"EN",
    "🇻🇮":"EN",
    "🇹🇻":"EN",
    "🇺🇦":"UK",
    "🇻🇪":"ES",
    "🇻🇦":"IT",
    "🇻🇺":"EN",
    "🇺🇾":"ES",
    "🇼🇫":"FR",
    "🇿🇲":"EN",
    "🇿🇼":"EN",
    "🇨🇵":"FR",
    "🇺🇲":"EN",
    "🇹🇦":"EN",
    "🇧🇻":"NB"
};

export const languagesMap:Record<string,string> = {
    "BG": "Bulgarian",
    "CS": "Czech",
    "DA": "Danish",
    "DE": "German",
    "EL": "Greek",
    "EN": "English",
    "ES": "Spanish",
    "ET": "Estonian",
    "FI": "Finnish",
    "FR": "French",
    "HU": "Hungarian",
    "ID": "Indonesian",
    "IT": "Italian",
    "JA": "Japanese",
    "KO": "Korean",
    "LT": "Lithuanian",
    "LV": "Latvian",
    "NB": "Norwegian",
    "NL": "Dutch",
    "PL": "Polish",
    "PT": "Portuguese",
    "RO":"Romanian",
    "RU":"Russian",
    "SK":"Slovak",
    "SL":"Slovenian",
    "SV":"Swedish",
    "TR":"Turkish",
    "UK":"Ukrainian",
    "ZH":"Chinese"
}; // (delete this) ^ Just to add in the title "English to Spanish" better than "US to ES"