name: Run tests
run-name: ${{ github.actor }} is running tests.
on:
  pull_request:

env:
    DEEPL_KEY: ${{ secrets.DEEPL_KEY }}
    DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    DISCORD_SECRET: ${{ secrets.DISCORD_SECRET }}
    DISCORD_DEV_SERVER_ID: ${{ secrets.DISCORD_DEV_SERVER_ID }}
    DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
    DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test